# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev linux-headers

WORKDIR /app

# Copy the project files into the container
COPY . .

# Fix the README filename expected by setup.py
RUN cp README.md readme.md

# Upgrade pip and install the package in editable mode
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -e .

# Expose port 8000 (if applicable)
EXPOSE 8000

# Set the default command to run the MCP server
CMD ["python", "-m", "weather_server.server"]
